//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYKHO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuNhap
    {
        public string maPhieuNhap { get; set; }
        public string maThietBi { get; set; }
        public int SoLuongNhap { get; set; }
        public decimal donGia { get; set; }
        public double thanhTien { get; set; }
    
        public virtual PhieuNhapHang PhieuNhapHang { get; set; }
        public virtual ThongTinThietBi ThongTinThietBi { get; set; }
    }
}
