//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYKHO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuXuat
    {
        public string maPhieuXuat { get; set; }
        public string maThietBi { get; set; }
        public int soLuong { get; set; }
        public double donGia { get; set; }
        public double thanhTien { get; set; }
    
        public virtual PhieuXuatHang PhieuXuatHang { get; set; }
        public virtual ThongTinThietBi ThongTinThietBi { get; set; }
    }
}
