//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYKHO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhapHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuNhapHang()
        {
            this.ChiTietPhieuNhap = new HashSet<ChiTietPhieuNhap>();
        }
    
        public string maPhieuNhap { get; set; }
        public string maNguoiDung { get; set; }
        public System.DateTime ngayNhap { get; set; }
        public string trangThai { get; set; }
        public string ghiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuNhap> ChiTietPhieuNhap { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
