//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYKHO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaiKhoan()
        {
            this.PhieuNhapHang = new HashSet<PhieuNhapHang>();
            this.PhieuXuatHang = new HashSet<PhieuXuatHang>();
        }
    
        public string maNguoiDung { get; set; }
        public string tenDangNhap { get; set; }
        public string matKhau { get; set; }
        public string maVaiTro { get; set; }
        public string hoVaTen { get; set; }
        public string email { get; set; }
        public string soDienThoai { get; set; }
        public string trangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuNhapHang> PhieuNhapHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuXuatHang> PhieuXuatHang { get; set; }
        public virtual VaiTro VaiTro { get; set; }
    }
}
