//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYKHO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinThietBi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThongTinThietBi()
        {
            this.ChiTietPhieuNhap = new HashSet<ChiTietPhieuNhap>();
            this.ChiTietPhieuXuat = new HashSet<ChiTietPhieuXuat>();
        }
    
        public string maThietBi { get; set; }
        public string maDanhMuc { get; set; }
        public string maNhaCungCap { get; set; }
        public string tenThietBi { get; set; }
        public string thoiGianBaoHanh { get; set; }
        public string model { get; set; }
        public string nhaSanXuat { get; set; }
        public string moTa { get; set; }
        public string trangThai { get; set; }
        public Nullable<int> soLuongCon { get; set; }
    
        public virtual DanhMucThietBi DanhMucThietBi { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuNhap> ChiTietPhieuNhap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuXuat> ChiTietPhieuXuat { get; set; }
    }
}
